package com.authflow.model.enums;

public enum ErrorCode {
	// Generic errors
	INTERNAL_SERVER_ERROR,
	VALIDATION_ERROR,
	RESOURCE_NOT_FOUND,
	UNAUTHORIZED,
	FORBIDDEN,
	RATE_LIMIT_EXCEEDED,

	// Authentication errors
	INVALID_CREDENTIALS,
	TOKEN_EXPIRED,
	TOKEN_INVALID,
	EMAIL_ALREADY_EXISTS,
	EMAIL_NOT_VERIFIED,
	INVALID_PROVIDER,

	// User errors
	USER_NOT_FOUND,

	// Request errors
	INVALID_REQUEST,
	MISSING_REQUIRED_FIELD,
	INVALID_FIELD_FORMAT,
	INVALID_FIELD_VALUE
}
